policies:
  - name: add-application-tag-to-all-s3-buckets
    resource: s3
    comment: |
      Add Application tag to all S3 Buckets
    filters:
      - "tag:Application": absent
    actions:
      - type: tag
        key: Application
        value: Unknown
      - type: notify
        template: default.html
        template_format: html
        priority_header: 1
        subject: "{{ account }} Added Application Tag to S3 Buckets"
        violation_desc: "Application tag added to these S3 Buckets:"
        action_desc: |
            "Actions Taken: The listed S3 Buckets had Application tag added with value of Unknown"
        to:
          - brian.gaber@compucom.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/472510080448/cloud-custodian
          region: us-east-1
