policies:
  - name: mod-s3-buckets-careguard-application-tag-value
    resource: s3
    comment: |
      Modify Application tag to all S3 Buckets with matching name
    filters:
      - or:
        - type: value
          key: Name
          op: contains
          value: "careguard"
        - type: value
          key: Name
          op: contains
          value: "Careguard"
        - type: value
          key: Name
          op: contains
          value: "cg"
    actions:
      - type: tag
        key: Application
        value: "Careguard"
      - type: tag
        key: Portfolio
        value: AiOps
      - type: notify
        template: default.html
        template_format: html
        priority_header: '1'
        violation_desc: "These S3 Buckets had Application tag value changed to Bonitasoft:"
        action_desc: |
            "Actions Taken: The listed S3 Buckets had Application tag value changed to Bonitasoft"
        subject: "{{ account }} Modifed Application Tag Value Of Some S3 Buckets"
        to:
          - brian.gaber@compucom.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/472510080448/cloud-custodian
